import { FormEvent, useEffect, useState } from "react";
import { Activity, Clock3, Play, Settings2 } from "lucide-react";
import { supabase } from "../lib/supabase";

type Job={id:string;job_type:string;status:string;parameters:Record<string,unknown>;created_at:string;started_at:string|null;completed_at:string|null;error_message:string|null};
type Run={id:string;run_name:string;parameters:Record<string,unknown>;events_detected:number;records_processed:number;created_at:string;status:string};

export default function EventDetection({projectId}:{projectId:string}){
 const [volWindow,setVolWindow]=useState(30),[retWindow,setRetWindow]=useState(30),[sigma,setSigma]=useState(3),[volMultiple,setVolMultiple]=useState(5),[minHistory,setMinHistory]=useState(30),[spacing,setSpacing]=useState(0);
 const [jobs,setJobs]=useState<Job[]>([]),[runs,setRuns]=useState<Run[]>([]),[message,setMessage]=useState("");
 async function load(){const[j,r]=await Promise.all([supabase.from('analysis_jobs').select('*').eq('project_id',projectId).eq('job_type','event_detection').order('created_at',{ascending:false}).limit(20),supabase.from('analysis_runs').select('*').eq('project_id',projectId).eq('run_type','abnormal_event_detection').order('created_at',{ascending:false}).limit(20)]);setJobs((j.data||[])as Job[]);setRuns((r.data||[])as Run[])}
 useEffect(()=>{load()},[projectId]);
 async function queue(e:FormEvent){e.preventDefault();setMessage('');const{error}=await supabase.from('analysis_jobs').insert({project_id:projectId,job_type:'event_detection',status:'queued',parameters:{volatility_window:retWindow,return_threshold_sigma:sigma,volume_window:volWindow,volume_multiple:volMultiple,minimum_history:minHistory,event_spacing_days:spacing}});if(error)setMessage(error.message);else{setMessage('Detection job queued. The analysis worker will process it automatically or when you run the Process Analysis Jobs workflow.');await load()}}
 return <section className="system-page"><div className="system-heading"><div><div className="eyebrow">REPRODUCIBLE SCREENING</div><h1>Event Detection</h1><p>Create, preserve, and compare abnormal-event screens without changing source code.</p></div></div>
 <div className="module-grid"><form className="control-card" onSubmit={queue}><div className="card-icon"><Settings2/></div><h2>Detection parameters</h2><div className="control-grid"><label>Return volatility window<input type="number" min="10" max="250" value={retWindow} onChange={e=>setRetWindow(+e.target.value)}/><small>Trading days</small></label><label>Return threshold<input type="number" min="1" max="10" step="0.1" value={sigma} onChange={e=>setSigma(+e.target.value)}/><small>Standard deviations</small></label><label>Volume window<input type="number" min="10" max="250" value={volWindow} onChange={e=>setVolWindow(+e.target.value)}/><small>Trading days</small></label><label>Volume threshold<input type="number" min="1" max="50" step="0.5" value={volMultiple} onChange={e=>setVolMultiple(+e.target.value)}/><small>Times rolling average</small></label><label>Minimum history<input type="number" min="10" max="250" value={minHistory} onChange={e=>setMinHistory(+e.target.value)}/><small>Rows before eligibility</small></label><label>Event spacing<input type="number" min="0" max="60" value={spacing} onChange={e=>setSpacing(+e.target.value)}/><small>Minimum days between events</small></label></div><button className="primary-action wide-button" type="submit"><Play size={17}/> Queue detection run</button>{message&&<div className="notice">{message}</div>}</form>
 <article className="control-card"><div className="card-icon"><Activity/></div><h2>Current production rule</h2><div className="rule-summary"><strong>30-day volatility · 3σ return · 30-day volume · 5× volume</strong><span>Current event file: 845 events across 354 symbols</span></div><p>The event day must satisfy both the return and volume conditions. Rolling statistics use prior observations only.</p><div className="warning-note">The preliminary note reports 843 events. Use a fresh run to reconcile the difference.</div></article></div>
 <section className="split-section"><article className="dashboard-card"><div className="eyebrow">JOB QUEUE</div><h2>Recent processing jobs</h2><div className="compact-list">{jobs.map(j=><div key={j.id}><span><strong>{j.status}</strong><small>{new Date(j.created_at).toLocaleString()}</small></span><span>{JSON.stringify(j.parameters)}</span></div>)}{!jobs.length&&<p>No queued jobs yet.</p>}</div></article><article className="dashboard-card"><div className="eyebrow">RUN HISTORY</div><h2>Completed detection runs</h2><div className="compact-list">{runs.map(r=><div key={r.id}><span><strong>{r.events_detected.toLocaleString()} events</strong><small>{new Date(r.created_at).toLocaleString()}</small></span><span>{r.records_processed.toLocaleString()} rows</span></div>)}{!runs.length&&<p>No completed runs yet.</p>}</div></article></section></section>
}
