import { FormEvent, useEffect, useState } from "react";
import { Calculator, Info, ShieldCheck } from "lucide-react";
import { supabase } from "../lib/supabase";

type EventRow={id:number;symbol:string;event_date:string;abnormal_return:number|null;volume_multiple:number|null;return_sigma:number|null;severity_score:number|null;insider_score:number|null;announcement_match:string|null;classification:string};
export default function InsiderAnalysis({projectId}:{projectId:string}){
 const [rows,setRows]=useState<EventRow[]>([]),[severity,setSeverity]=useState(35),[volume,setVolume]=useState(25),[sigma,setSigma]=useState(25),[unexplained,setUnexplained]=useState(15),[message,setMessage]=useState('');
 async function load(){const{data}=await supabase.from('research_events').select('id,symbol,event_date,abnormal_return,volume_multiple,return_sigma,severity_score,insider_score,announcement_match,classification').eq('project_id',projectId).order('insider_score',{ascending:false,nullsFirst:false}).limit(200);setRows((data||[])as EventRow[])}
 useEffect(()=>{load()},[projectId]);
 async function recalc(e:FormEvent){e.preventDefault();setMessage('');const total=severity+volume+sigma+unexplained;if(total!==100){setMessage('Weights must total 100.');return}const{error}=await supabase.rpc('recalculate_event_scores',{p_project_id:projectId,p_severity_weight:severity,p_volume_weight:volume,p_sigma_weight:sigma,p_unexplained_weight:unexplained});if(error)setMessage(error.message);else{setMessage('Scores recalculated.');await load()}}
 return <section className="system-page"><div className="system-heading"><div><div className="eyebrow">SCREENING INDICATOR</div><h1>Insider Analysis</h1><p>Rank events for further review without treating the score as proof of misconduct.</p></div><div className="ethical-badge"><ShieldCheck size={18}/> Screening only</div></div>
 <div className="module-grid"><form className="control-card" onSubmit={recalc}><div className="card-icon"><Calculator/></div><h2>Indicator weights</h2><div className="weight-list"><Weight label="Overall severity" value={severity} set={setSeverity}/><Weight label="Abnormal volume" value={volume} set={setVolume}/><Weight label="Return sigma" value={sigma} set={setSigma}/><Weight label="No announcement match" value={unexplained} set={setUnexplained}/></div><div className="weight-total">Total: {severity+volume+sigma+unexplained}%</div><button className="primary-action wide-button" type="submit">Recalculate all event scores</button>{message&&<div className="notice">{message}</div>}</form><article className="control-card"><div className="card-icon"><Info/></div><h2>Interpretation</h2><p>The score combines event severity, volume intensity, return extremity, and whether the event currently lacks a matched public disclosure.</p><div className="score-scale"><span><b>0–39</b> Low indication</span><span><b>40–69</b> Moderate indication</span><span><b>70–100</b> High-priority review</span></div><div className="warning-note">Legal conclusions require trader-level records, identities, timing, communications, and applicable law.</div></article></div>
 <div className="data-table-wrap"><table className="system-table"><thead><tr><th>Rank</th><th>Symbol</th><th>Date</th><th>Insider score</th><th>Severity</th><th>Volume</th><th>Return sigma</th><th>Announcement</th><th>Classification</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td><strong>{r.symbol}</strong></td><td>{r.event_date}</td><td><span className="score-badge">{fmt(r.insider_score)}</span></td><td>{fmt(r.severity_score)}</td><td>{fmt(r.volume_multiple)}×</td><td>{fmt(r.return_sigma)}σ</td><td>{r.announcement_match||'Unmatched'}</td><td>{r.classification}</td></tr>)}</tbody></table></div></section>
}
function Weight({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label><span>{label}</span><input type="range" min="0" max="100" value={value} onChange={e=>set(+e.target.value)}/><strong>{value}%</strong></label>}
function fmt(v:number|null){return v==null?'—':Number(v).toFixed(1)}
