import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Database, Download, Search } from "lucide-react";
import { supabase } from "../lib/supabase";
const PAGE_SIZE = 100;
type Row = { id:number; symbol:string; trade_date:string; open_price:number|null; high_price:number|null; low_price:number|null; close_price:number|null; volume:number|null; stock_return:number|null; market_return:number|null; abnormal_return:number|null; };
export default function MarketDatabase({ projectId }: { projectId: string }) {
  const [rows,setRows]=useState<Row[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(0);
  const [symbol,setSymbol]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[onlyExtreme,setOnlyExtreme]=useState(false);
  async function load(){let q=supabase.from("research_market_data").select("*",{count:"exact"}).eq("project_id",projectId).order("trade_date",{ascending:false}).range(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE-1);if(symbol.trim())q=q.ilike("symbol",`%${symbol.trim()}%`);if(from)q=q.gte("trade_date",from);if(to)q=q.lte("trade_date",to);if(onlyExtreme)q=q.or("abnormal_return.gte.0.05,abnormal_return.lte.-0.05");const{data,count:total}=await q;setRows((data||[])as Row[]);setCount(total||0);}
  useEffect(()=>{load();},[projectId,page,symbol,from,to,onlyExtreme]);
  function exportCsv(){const h=["Symbol","Date","Open","High","Low","Close","Volume","Stock Return","Market Return","Abnormal Return"];const b=rows.map(r=>[r.symbol,r.trade_date,r.open_price,r.high_price,r.low_price,r.close_price,r.volume,r.stock_return,r.market_return,r.abnormal_return]);const csv=[h,...b].map(line=>line.map(v=>`"${v??""}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="filtered-market-data.csv";a.click();URL.revokeObjectURL(url);}
  const pages=Math.max(1,Math.ceil(count/PAGE_SIZE));
  return <section className="system-page"><div className="system-heading"><div><div className="eyebrow">STOCK-DAY DATABASE</div><h1>Market Database</h1><p>Query the imported research panel without loading the full dataset into the browser.</p></div><button className="primary-action" onClick={exportCsv}><Download size={16}/> Export current page</button></div>
  {count===0&&<div className="import-notice"><Database size={24}/><div><strong>The database table is ready but the 530,674-row research CSV has not been imported yet.</strong><span>Upload the file in Research Files, then run the included “Import Market Dataset” GitHub Action.</span></div></div>}
  <div className="filter-panel"><div className="search-field"><Search size={16}/><input value={symbol} onChange={e=>{setPage(0);setSymbol(e.target.value)}} placeholder="Symbol"/></div><input type="date" value={from} onChange={e=>{setPage(0);setFrom(e.target.value)}}/><input type="date" value={to} onChange={e=>{setPage(0);setTo(e.target.value)}}/><label className="inline-check"><input type="checkbox" checked={onlyExtreme} onChange={e=>{setPage(0);setOnlyExtreme(e.target.checked)}}/> |AR| ≥ 5%</label></div>
  <div className="data-table-wrap"><table className="system-table"><thead><tr><th>Symbol</th><th>Date</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th><th>Return</th><th>Market</th><th>Abnormal</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.symbol}</strong></td><td>{r.trade_date}</td><td>{fmt(r.open_price)}</td><td>{fmt(r.high_price)}</td><td>{fmt(r.low_price)}</td><td>{fmt(r.close_price)}</td><td>{r.volume?.toLocaleString()??"—"}</td><td>{pct(r.stock_return)}</td><td>{pct(r.market_return)}</td><td className={(r.abnormal_return||0)>=0?"positive":"negative"}>{pct(r.abnormal_return)}</td></tr>)}{!rows.length&&<tr><td colSpan={10} className="empty-cell">No imported market rows match the filters.</td></tr>}</tbody></table></div><div className="pagination"><button disabled={page===0} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/> Previous</button><span>{count.toLocaleString()} rows · Page {page+1} of {pages}</span><button disabled={page+1>=pages} onClick={()=>setPage(page+1)}>Next <ChevronRight size={16}/></button></div></section>;
}
function fmt(v:number|null){return v==null?"—":Number(v).toFixed(2)} function pct(v:number|null){return v==null?"—":`${(Number(v)*100).toFixed(2)}%`}
