import { FormEvent, useEffect, useState } from "react";
import { Activity, Play, TrendingDown } from "lucide-react";
import { supabase } from "../lib/supabase";
type Cycle={id:string;symbol:string;start_date:string;peak_date:string;end_date:string;run_up_return:number|null;peak_volume_multiple:number|null;reversal_return:number|null;cycle_days:number|null;pump_score:number|null;status:string};
export default function PumpAnalysis({projectId}:{projectId:string}){
 const[runUp,setRunUp]=useState(15),[reversal,setReversal]=useState(-10),[forward,setForward]=useState(10),[volume,setVolume]=useState(5),[cycles,setCycles]=useState<Cycle[]>([]),[message,setMessage]=useState('');
 async function load(){const{data}=await supabase.from('pump_cycles').select('*').eq('project_id',projectId).order('pump_score',{ascending:false,nullsFirst:false}).limit(500);setCycles((data||[])as Cycle[])}useEffect(()=>{load()},[projectId]);
 async function queue(e:FormEvent){e.preventDefault();const{error}=await supabase.from('analysis_jobs').insert({project_id:projectId,job_type:'pump_detection',status:'queued',parameters:{minimum_run_up_percent:runUp,maximum_reversal_percent:reversal,forward_window_days:forward,minimum_volume_multiple:volume}});if(error)setMessage(error.message);else setMessage('Pump-cycle job queued. Run or wait for the Process Analysis Jobs workflow.')}
 return <section className="system-page"><div className="system-heading"><div><div className="eyebrow">CYCLE DETECTION</div><h1>Pump-and-Dump Analysis</h1><p>Identify run-up, peak, and reversal cycles for structured manual review.</p></div><div className="record-count">{cycles.length} stored cycles</div></div><div className="module-grid"><form className="control-card" onSubmit={queue}><div className="card-icon"><Activity/></div><h2>Cycle parameters</h2><div className="control-grid"><label>Minimum run-up<input type="number" value={runUp} onChange={e=>setRunUp(+e.target.value)}/><small>Percent</small></label><label>Maximum reversal<input type="number" value={reversal} onChange={e=>setReversal(+e.target.value)}/><small>Percent</small></label><label>Forward window<input type="number" value={forward} onChange={e=>setForward(+e.target.value)}/><small>Trading days</small></label><label>Minimum peak volume<input type="number" step="0.5" value={volume} onChange={e=>setVolume(+e.target.value)}/><small>Times average</small></label></div><button className="primary-action wide-button"><Play size={17}/> Queue pump-cycle run</button>{message&&<div className="notice">{message}</div>}</form><article className="control-card"><div className="card-icon"><TrendingDown/></div><h2>Detection logic</h2><p>A candidate begins with a material run-up and abnormal volume, reaches a local peak, and then falls by the required reversal threshold within the selected forward window.</p><div className="warning-note">Candidates remain unconfirmed until corporate actions, announcements, liquidity, and data quality are reviewed.</div></article></div><div className="data-table-wrap"><table className="system-table"><thead><tr><th>Symbol</th><th>Start</th><th>Peak</th><th>End</th><th>Run-up</th><th>Peak volume</th><th>Reversal</th><th>Days</th><th>Score</th><th>Status</th></tr></thead><tbody>{cycles.map(c=><tr key={c.id}><td><strong>{c.symbol}</strong></td><td>{c.start_date}</td><td>{c.peak_date}</td><td>{c.end_date}</td><td className="positive">{pct(c.run_up_return)}</td><td>{fmt(c.peak_volume_multiple)}×</td><td className="negative">{pct(c.reversal_return)}</td><td>{c.cycle_days??'—'}</td><td><span className="score-badge">{fmt(c.pump_score)}</span></td><td>{c.status}</td></tr>)}{!cycles.length&&<tr><td colSpan={10} className="empty-cell">No cycles have been generated yet. Queue a run after importing the market database.</td></tr>}</tbody></table></div></section>
}
function fmt(v:number|null){return v==null?'—':Number(v).toFixed(1)}function pct(v:number|null){return v==null?'—':`${(Number(v)*100).toFixed(2)}%`}
