import { createClient } from "@supabase/supabase-js";
import { createHash } from "node:crypto";
const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Missing Supabase secrets.");
const sb=createClient(url,key,{auth:{persistSession:false}});
type Item={source_name:string;source_type:string;source_url:string;title:string;published_at:string|null;summary:string|null;symbol:string|null;company_name:string|null;authority_score:number};
const sources=[
 {name:"SEBON Notices",type:"regulator",url:"https://sebon.gov.np/index.php/notices",score:95},
 {name:"SEBON News",type:"regulator",url:"https://sebon.gov.np/news",score:92},
 {name:"SEBON Prospectus",type:"regulator",url:"https://sebon.gov.np/prospectus",score:95},
 {name:"SEBON Public Issues",type:"regulator",url:"https://sebon.gov.np/index.php/public-issues-data",score:95}
];
const clean=(s:string)=>s.replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();
async function aliases(){const{data}=await sb.from("company_aliases").select("symbol,company_name,aliases");return data||[]}
function identify(title:string,rows:any[]){const normalized=title.toLowerCase();for(const r of rows){const names=[r.symbol,r.company_name,...(r.aliases||[])].filter(Boolean).map((x:string)=>String(x).toLowerCase());if(names.some((x:string)=>x.length>2&&new RegExp(`(^|[^a-z0-9])${x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}([^a-z0-9]|$)`,"i").test(normalized)))return{symbol:r.symbol,company_name:r.company_name}}return{symbol:null,company_name:null}}
function parsePage(html:string,base:string,meta:any,rows:any[]){const out:Item[]=[];const rx=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=rx.exec(html))){const title=clean(m[2]);if(title.length<12||/^(home|more|english|nepali|next|previous)$/i.test(title))continue;const href=new URL(m[1],base).toString();if(!href.includes(new URL(base).hostname))continue;const context=clean(html.slice(Math.max(0,m.index-250),Math.min(html.length,m.index+350)));const dm=context.match(/(20\d{2})[-/.](\d{1,2})[-/.](\d{1,2})/);const published=dm?new Date(`${dm[1]}-${dm[2].padStart(2,"0")}-${dm[3].padStart(2,"0")}T00:00:00Z`).toISOString():null;const id=identify(title,rows);out.push({source_name:meta.name,source_type:meta.type,source_url:href,title,published_at:published,summary:null,symbol:id.symbol,company_name:id.company_name,authority_score:meta.score})}return [...new Map(out.map(x=>[x.source_url,x])).values()].slice(0,300)}
async function gdelt(rows:any[]){const q=encodeURIComponent('("Nepal Stock Exchange" OR NEPSE)');const endpoint=`https://api.gdeltproject.org/api/v2/doc/doc?query=${q}&mode=ArtList&format=json&maxrecords=150&sort=HybridRel`;try{const r=await fetch(endpoint,{signal:AbortSignal.timeout(30000)});if(!r.ok)return[];const j:any=await r.json();return (j.articles||[]).map((a:any)=>{const id=identify(a.title||"",rows);return{source_name:a.domain||"GDELT News",source_type:"news",source_url:a.url,title:a.title||"Untitled",published_at:a.seendate?new Date(a.seendate).toISOString():null,summary:null,symbol:id.symbol,company_name:id.company_name,authority_score:55}}).filter((x:any)=>x.source_url&&x.title)}catch{return[]}}
const aliasRows=await aliases();let items:Item[]=[];for(const source of sources){console.log(`Fetching ${source.name}`);try{const r=await fetch(source.url,{headers:{"user-agent":"NEPSE-Research-Evidence-Bot/1.0"},signal:AbortSignal.timeout(30000)});if(!r.ok){console.warn(`${source.name}: ${r.status}`);continue}items.push(...parsePage(await r.text(),source.url,source,aliasRows))}catch(e){console.warn(source.name,e)}}items.push(...await gdelt(aliasRows));items=[...new Map(items.map(x=>[x.source_url,x])).values()];let saved=0;for(let i=0;i<items.length;i+=200){const chunk=items.slice(i,i+200).map(x=>({...x,content_hash:createHash("sha256").update(`${x.source_url}|${x.title}`).digest("hex"),fetched_at:new Date().toISOString()}));const{error}=await sb.from("internet_evidence").upsert(chunk,{onConflict:"content_hash"});if(error)throw error;saved+=chunk.length}console.log(`Saved ${saved} public evidence items.`)
