import { useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { AlertTriangle, BarChart3, BookOpen, Database, FileDown, FolderOpen, Images, LogOut, Megaphone, Search, Settings, ShieldAlert, SlidersHorizontal, StickyNote } from "lucide-react";
import { supabase } from "./lib/supabase";
import Login from "./components/Login";
import Dashboard from "./components/Dashboard";
import FiguresGallery from "./components/FiguresGallery";
import DataCatalog from "./components/DataCatalog";
import FilesPanel from "./components/FilesPanel";
import DecisionsPanel from "./components/DecisionsPanel";
import EventExplorer from "./components/EventExplorer";
import MarketDatabase from "./components/MarketDatabase";
import DataQuality from "./components/DataQuality";
import Announcements from "./components/Announcements";
import ResearchFindings from "./components/ResearchFindings";
type Tab="dashboard"|"sources"|"market"|"detection"|"events"|"insider"|"pump"|"announcements"|"figures"|"quality"|"findings"|"decisions"|"files"|"exports"|"admin";
export default function App(){const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[projectId,setProjectId]=useState(""),[sections,setSections]=useState<any[]>([]),[tab,setTab]=useState<Tab>("dashboard"),[error,setError]=useState("");
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(session)loadWorkspace()},[session]);
async function loadWorkspace(){setError("");const{data:memberships,error:membershipError}=await supabase.from("project_members").select("project_id").limit(1);if(membershipError||!memberships?.length){setError("Your account is not approved for this private workspace.");return}const pid=memberships[0].project_id as string;setProjectId(pid);const{data}=await supabase.from("paper_sections").select("*").eq("project_id",pid).order("sort_order");setSections(data||[])}
if(loading)return <div className="center">Loading...</div>;if(!session)return <Login/>;
const nav=[["dashboard","Dashboard",<BarChart3 size={18}/>],["sources","Data Sources",<Database size={18}/>],["market","Market Database",<Search size={18}/>],["detection","Event Detection",<SlidersHorizontal size={18}/>],["events","Event Explorer",<ShieldAlert size={18}/>],["insider","Insider Analysis",<Search size={18}/>],["pump","Pump-and-Dump",<AlertTriangle size={18}/>],["announcements","Announcements",<Megaphone size={18}/>],["figures","Figures and Tables",<Images size={18}/>],["quality","Data Quality",<ShieldAlert size={18}/>],["findings","Research Findings",<StickyNote size={18}/>],["decisions","Research Decisions",<BookOpen size={18}/>],["files","Research Files",<FolderOpen size={18}/>],["exports","Exports",<FileDown size={18}/>],["admin","Admin",<Settings size={18}/>]]as const;
return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-icon"><BookOpen size={24}/></div><div><strong>NEPSE Research</strong><span>Intelligence System</span></div></div><nav className="main-nav system-nav">{nav.map(([key,label,icon])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key as Tab)}>{icon}{label}</button>)}</nav><div className="sidebar-bottom"><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}><LogOut size={16}/> Sign out</button></div></aside><main className="workspace">{error&&<div className="error-banner">{error}</div>}{!error&&tab==="dashboard"&&projectId&&<Dashboard projectId={projectId} sections={sections}/>} {!error&&tab==="sources"&&projectId&&<DataCatalog projectId={projectId}/>} {!error&&tab==="market"&&projectId&&<MarketDatabase projectId={projectId}/>} {!error&&tab==="events"&&projectId&&<EventExplorer projectId={projectId}/>} {!error&&tab==="announcements"&&<Announcements/>} {!error&&tab==="figures"&&<FiguresGallery/>} {!error&&tab==="quality"&&projectId&&<DataQuality projectId={projectId}/>} {!error&&tab==="findings"&&<ResearchFindings/>} {!error&&tab==="decisions"&&projectId&&<DecisionsPanel projectId={projectId}/>} {!error&&tab==="files"&&projectId&&<FilesPanel projectId={projectId}/>} {!error&&["detection","insider","pump","exports","admin"].includes(tab)&&<ComingSoon title={nav.find(n=>n[0]===tab)?.[1]||""}/>}</main></div>}
function ComingSoon({title}:{title:string}){return <section className="system-page"><div className="system-heading"><div><div className="eyebrow">NEXT MODULE</div><h1>{title}</h1><p>The database foundation is now ready. This module will be connected to reproducible analysis runs in the next build.</p></div></div><div className="coming-card"><SlidersHorizontal size={34}/><h2>Module scaffold ready</h2><p>Event Explorer, Market Database, Announcements, and Data Quality are implemented first because they are the foundation for scoring and classification.</p></div></section>}
