import { useEffect,useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { BarChart3,BookOpen,Database,GitCompareArrows,LogOut,Search,Settings,ShieldAlert,Wifi } from "lucide-react";
import { supabase } from "./lib/supabase";
import Login from "./components/Login";import PublicPortal from "./components/PublicPortal";import Dashboard from "./components/Dashboard";import CrossReferenceAnalysis from "./components/CrossReferenceAnalysis";import InvestigationsHub from "./components/InvestigationsHub";import MarketHub from "./components/MarketHub";import EvidenceHub from "./components/EvidenceHub";import ResearchHub from "./components/ResearchHub";import SettingsHub from "./components/SettingsHub";
type Tab="dashboard"|"investigations"|"crossref"|"market"|"evidence"|"research"|"settings";
export default function App(){if(window.location.pathname!=="/login"&&!window.location.pathname.startsWith("/workspace")){return <PublicPortal/>;}const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[projectId,setProjectId]=useState(""),[tab,setTab]=useState<Tab>("dashboard"),[error,setError]=useState("");useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);useEffect(()=>{if(session)loadWorkspace()},[session]);async function loadWorkspace(){setError("");const{data,error}=await supabase.from("project_members").select("project_id").limit(1);if(error||!data?.length){setError("Your account is not approved for this private workspace.");return}setProjectId(data[0].project_id)}if(loading)return <div className="center">Loading…</div>;if(!session)return <Login/>;const nav=[
["dashboard","Overview",<BarChart3 size={18}/>],
["investigations","Investigations",<ShieldAlert size={18}/>],
["crossref","Cross-reference",<GitCompareArrows size={18}/>],
["market","Market & companies",<Search size={18}/>],
["evidence","Public evidence",<Wifi size={18}/>],
["research","Research outputs",<BookOpen size={18}/>],
["settings","Settings",<Settings size={18}/>]
] as const;return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-icon"><Database size={22}/></div><div><strong>NEPSE Integrity</strong><span>Research workspace</span></div></div><div className="sidebar-caption">WORKSPACE</div><nav className="main-nav system-nav">{nav.map(([key,label,icon])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key as Tab)}>{icon}<span>{label}</span></button>)}</nav><div className="sidebar-status"><span className="status-dot"/>Evidence engine online</div><div className="sidebar-bottom"><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}><LogOut size={16}/> Sign out</button></div></aside><main className="workspace"><div className="mobile-topbar"><strong>NEPSE Integrity</strong><select value={tab} onChange={e=>setTab(e.target.value as Tab)}>{nav.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>{error&&<div className="error-banner">{error}</div>}{!error&&projectId&&<>{tab==="dashboard"&&<Dashboard projectId={projectId}/>} {tab==="investigations"&&<InvestigationsHub projectId={projectId}/>} {tab==="crossref"&&<CrossReferenceAnalysis projectId={projectId}/>} {tab==="market"&&<MarketHub projectId={projectId}/>} {tab==="evidence"&&<EvidenceHub projectId={projectId}/>} {tab==="research"&&<ResearchHub projectId={projectId}/>} {tab==="settings"&&<SettingsHub projectId={projectId}/>}</>}</main></div>}
